const BALL_DIAMETER = 20;
const BLOCK_HEIGHT = 15;
const BLOCK_WIDTH = 75;
const BLOCK_PADDING = 16;
const CONTAINER_HEIGHT = 500;
const CONTAINER_WIDTH = 750;
const COLUMNS = 5;
const ROWS = 3;
const LAYOUT_WIDTH = (BLOCK_WIDTH * COLUMNS) + (BLOCK_PADDING * (COLUMNS - 1));
const FPS = 1000 / 60;

export {
    BALL_DIAMETER,
    BLOCK_HEIGHT,
    BLOCK_WIDTH,
    BLOCK_PADDING,
    CONTAINER_HEIGHT,
    CONTAINER_WIDTH,
    COLUMNS,
    ROWS,
    LAYOUT_WIDTH,
    FPS,
};
